[package]
name = "marktest"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
skeptic = "0.13.7"

[build-dependencies]
skeptic = "0.13.0"
